import "./globals.css";
import Hero from "./components/Hero"
import Hero2 from "./components/Hero2";
import Hero3 from "./components/Hero3";
import type { Metadata } from "next"
import { Inter } from "next/font/google"



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          
          <Hero />
          <Hero2 />
          <Hero3 />
        {children}
        
        </body>
    </html>
  );
}
